import Header, { HeaderMenuItemTypes } from "@/components/organisms/Header";
import { rem } from "@/styles/mixins";
import { Box, Typography } from "@mui/material";
import Head from "next/head";
import { useMemo } from "react";

interface MainLayoutProps {
  children: React.ReactElement;
}

const MainLayout: React.FC<MainLayoutProps> = ({children}) => {
  const headerMenuList = useMemo<HeaderMenuItemTypes[]>(() => {
    return [
      {label: 'Trending', href: '#'},
      {label: 'Rewards', href: '#'},
      {label: 'Gift Cards', href: '#'},
      {label: 'Reserve', href: '#'},
      {label: 'Delivery', href: '#'},
    ]
  }, []);
  return (
    <Box className='t-mainLayout'
      sx={{backgroundColor: 'background.paper'}}
    >
      <Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
      <Box component='header' sx={{pt: rem(83)}}>
        <Header menuList={headerMenuList} />
      </Box>
      <Box component='main'>
        {children}
      </Box>
      </Box>
    </Box>
  )
}

export default MainLayout;